package com.myspace.javadmn;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Shipment {

	private java.lang.Integer distance;
	private java.lang.Integer price;

	public Shipment() {
	}

	public java.lang.Integer getDistance() {
		return this.distance;
	}

	public void setDistance(java.lang.Integer distance) {
		this.distance = distance;
	}

	public java.lang.Integer getPrice() {
		return this.price;
	}

	public void setPrice(java.lang.Integer price) {
		this.price = price;
	}
}