package com.myspace.javadmn;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import org.drools.core.ClassObjectFilter;
import org.kie.api.KieServices;
import org.kie.api.command.Command;
import org.kie.api.runtime.ExecutionResults;
import org.kie.api.runtime.KieContainer;
import org.kie.api.runtime.StatelessKieSession;
import org.kie.internal.command.CommandFactory;

/**
 * This class was automatically generated by the data modeler tool.
**/
public class Utils {

	static final long serialVersionUID = 1L;
	private static KieServices ks = KieServices.Factory.get();
    private static KieContainer kieContainer = ks.getKieClasspathContainer(Utils.class.getClassLoader());

	public Utils() {
	}
	
	public static Integer xlsKnowledge(Integer distance) {
        System.out.println("Inside xlsKnowledge method...");
        Integer result = 0;
        System.out.println("Result contains: " + result);
        return result;
    }
}